"""Initial migration

Revision ID: 605f1bad981c
Revises: c7df473c048c
Create Date: 2025-03-31 08:56:53.835487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605f1bad981c'
down_revision = 'c7df473c048c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('power',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero_power',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('power_id', sa.Integer(), nullable=False),
    sa.Column('strength', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hero_id'], ['hero.id'], ),
    sa.ForeignKeyConstraint(['power_id'], ['power.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.add_column(sa.Column('super_name', sa.String(), nullable=False))
        batch_op.drop_column('superpower')
        batch_op.drop_column('alias')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alias', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('superpower', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('super_name')

    op.drop_table('hero_power')
    op.drop_table('power')
    # ### end Alembic commands ###
